# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false

# upload coverage statistics upon successful completion of tets
codecov: true
coveralls: true
